electionapp/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('electionapp.views',
	url(r'^$', 			'index'),
    url(r'^polls/$',    'polls_overview'),
    url(r'^users/$',    'users_overview'),
    url(r'^ballots/$',    'ballots_overview'),
    url(r'^results/$',    'results_overview'),
    url(r'^login/$', 'login'),
    url(r'^logout/$', 'logout'),
	url(r'^about/$', 	'about'),
	url(r'^systems/$', 	'systems'),
	url(r'^create/$', 	'create'),
	url(r'^dashboard/$', 'dashboard'),
	url(r'^account/$', 	'account'),
    url(r'^(\w+)/$', 'analyze_key'),
    url(r'^(\w+)/close/$', 'close_election'),
    url(r'^(\w+)/edit/$', 'edit_vote'),
    url(r'^(\w+)/close/(\w+)$', 'close_election'), #dev only
    url(r'^(\w+)/delete$', 'delete_election'), #dev only
    url(r'^vote/$', 'vote'),
)

waggle/urls.py
from django.conf.urls import patterns, include, url

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
	url('', include('electionapp.urls')),
)

handler404 = 'electionapp.views.custom_404'

electionapp/forms.py
#-*- coding: utf-8 -*-
from django import forms
from models import *
from django.forms.formsets import BaseFormSet


class LoginForm(forms.Form):
    username = forms.CharField(label='Email', max_length=30)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class AccountCreationForm(forms.Form):
    name = forms.CharField(label='Name', required=True)
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput, required=True)
    password_check = forms.CharField(label='Password verification', widget=forms.PasswordInput, required=True)

class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

class RGVCustomForm(forms.Form):
    min = forms.IntegerField(required=False, initial=0, widget=forms.HiddenInput()) #TODO : handle dynamically 'required' argument
    max = forms.IntegerField(required=False, initial=20, widget=forms.HiddenInput())

class FPPCustomForm(forms.Form):
    useless = forms.IntegerField(required=False, widget=forms.HiddenInput())

class BDACustomForm(forms.Form):
    useless = forms.IntegerField(required=False, widget=forms.HiddenInput())

class CandidateForm(forms.Form):
    name = forms.CharField(min_length=1,max_length=140, required=True)

class EmailGuestForm(forms.Form):
    email = forms.EmailField(required=False)

class ElectionForm(forms.Form):
    name = forms.CharField(min_length=2, max_length=140, required=True, label='Name of the poll')
    message = forms.CharField(min_length=0, max_length=1000, label='Message to the voters', required=False, widget=forms.Textarea)
    type = forms.ChoiceField(choices=[(1,'Only guests are allowed to vote. You will invite them by email.'),(2,'You invite people with an url that anyone can use as many times as one wants.')], widget=forms.RadioSelect, required=True, label='Voting mode')
    system = forms.ChoiceField(choices=[(s.key,s.name) for s in System.objects.all()], required=True)

class CreatorForm(forms.Form):
    name = forms.CharField(min_length=2, max_length=140, required=True)
    email = forms.EmailField(required=False)
    invite_me = forms.BooleanField(required=False, label="I'm voting too")

class BallotForm(forms.Form):
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', None)
        custom = kwargs.pop('custom', None)
        super(BallotForm, self).__init__(*args, **kwargs)
        self.choices = choices
        self.custom = custom
        self.requires_ranking = False

class FPPBallotForm(BallotForm):
    def __init__(self, *args, **kwargs):
        super(FPPBallotForm, self).__init__(*args, **kwargs)
        self.fields['candidates'].choices = self.choices
    candidates = forms.ChoiceField(choices=(), widget=forms.RadioSelect, required=True)

class BDABallotForm(BallotForm):
    def __init__(self, *args, **kwargs):
        super(BDABallotForm, self).__init__(*args, **kwargs)
        self.requires_ranking = True
    ranking = forms.CharField(max_length=1000, required=True, widget=forms.HiddenInput())

class RGVBallotForm(BallotForm):
    def __init__(self, *args, **kwargs):
        super(RGVBallotForm, self).__init__(*args, **kwargs)
        for choice in self.choices:
            self.fields[choice[0]] = forms.IntegerField(max_value=self.custom['max'], min_value=self.custom['min'],label=choice[1], required=True)

electionapp/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render
from django.template import RequestContext
from django.http import HttpResponse, Http404
from django.forms.formsets import formset_factory
from models import *
from results import *
import datetime
from electionapp.settings import *
from electionapp.forms import *
import time
import tools
from django.core.urlresolvers import reverse
from mongoengine.django.auth import *
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout

def polls_overview(request):
	elections = Election.objects.order_by('-creation_date')
	return render_to_response('polls.html', {'Elections': elections},context_instance=RequestContext(request))

def users_overview(request):
    users = MyUser.objects.order_by('-date')
    return render_to_response('users.html', {'Users': users},context_instance=RequestContext(request))

def ballots_overview(request):
    ballots = Ballot.objects.order_by('-date')
    return render_to_response('ballots.html', {'Ballots': ballots},context_instance=RequestContext(request))

def results_overview(request):
    results = Result.objects.order_by('-date')
    return render_to_response('results.html', {'Results': results},context_instance=RequestContext(request))

def index(request):
	return render_to_response('index.html',context_instance=RequestContext(request))

def analyze_key(request, key):
    if len(key) >= KEYA_LEN: #if key is long enough to identify a keyA
        keyA = key[:KEYA_LEN]
        election = Election.objects(key=keyA) #retrieve election data for keyA
        if len(election)==1: #if an election with id keyA was found
            election = election[0]
            keyB = key[KEYA_LEN:]
            if election['type']==1: #if election is private
                if len(keyB) == KEYB_LEN:
                    if keyB==election['admin_key']:
                        return admin_election(request, election)
                    else:
                        if keyB in election['guests']: #if keyB is a guest key
                            if election['open']:
                                ballots = Ballot.objects(election=election, user=election['guests'][keyB])
                                if ballots.count()==0: #TODO : distinguish
                                    return vote(request, election, user=election['guests'][keyB], user_key=keyB)
                                else:
                                    return vote(request, election, user=election['guests'][keyB], user_key=keyB, already_voted=True)
                            else:
                                return view_results(request, election)
                        else:
                            raise Http404
                else:
                    if election['open']:
                        return view_results(request, election)
                    else:
                        return view_results(request, election)
            elif election['type']==2: #else if election is public #TO BE TESTED
                if len(keyB) == KEYB_LEN:
                    if keyB == election['admin_key']: #if keyB is the admin key
                        return admin_election(request, election)
                    else:
                        raise Http404
                elif keyB == '':
                    if election['open']:
                        return vote(request, election)
                    else:
                        return view_results(request, election)
                else:
                    raise Http404
            else:
                raise Http404
        elif len(election)>1:
            raise Http404
            #TODO : raise error, because getting here means that more than 1 election with key keyA has been found
        else:
            raise Http404
    else:
        raise Http404

def admin_election(request, election):
    return render_to_response('admin_election.html', {'election': election}, context_instance=RequestContext(request))

def view_results(request, election):
    election = check_and_compute(election)
    return render_to_response('view_results.html', {'election': election}, context_instance=RequestContext(request))

def close_election(request, key, open=False):
    #TODO : check if keys are ok here (important)
    election_key = key[:KEYA_LEN]
    admin_key = key[KEYA_LEN:]
    election = Election.objects(key=election_key)
    if len(election)==1: # if the election was found
        election=election[0]
        if election.admin_key==admin_key:
            if open: #for dev only
                election.open=True
                del election.closing_date
                election.save()
                return admin_election(request,election)
            else:
                election.open=False
                election.closing_date=datetime.datetime.now()
                election.save()
                return view_results(request,election)
        else:
            raise Http404
    else:
        raise Http404

def edit_vote(request,key):
    election_key = key[:KEYA_LEN]
    user_key = key[KEYA_LEN:]
    election = Election.objects(key=election_key)
    if len(election)==1: # if the election was found
        election=election[0]
        if user_key in election['guests']:
            if election['open']:
                ballots = Ballot.objects(election=election, user=election['guests'][user_key])
                if ballots.count()==0: #TODO : distinguish
                    raise Http404
                else:
                    return vote(request, election, user=election['guests'][user_key], user_key=user_key, already_voted=True, edit_vote=True)
            else:
                return view_results(request, election)
        else:
            raise Http404
    else:
        raise Http404

def vote(request, election, user=None, user_key='', already_voted=False, edit_vote=False):
    #TODO: adapt to multiple systems
    my_choices = []
    for key, value in election.candidates.items():
        my_choices.append((key,value))
    if request.method == 'POST':
        for election_system in election.systems:
            method_name = election_system.system.key + 'BallotForm'
            method = globals()[method_name]
            form = method(request.POST, choices=my_choices, custom=election_system.custom)
        if form.is_valid():
            if user==None:
                user = MyUser(ip=tools.get_ip(request), type=9)
                user.save()
            if already_voted:
                prev_ballots = Ballot.objects(user=user,election=election)
                for ballot in prev_ballots:
                    ballot.delete()
            cast_ballot(form.cleaned_data, user, election.systems[0].system, election)
            return render_to_response('voting_page.html', {'form':form, 'send':True, 'election':election, 'user_key':user_key, 'show_already_voted':False, 'show_form':False, 'show_edit':edit_vote, 'show_vote_cast':True}, context_instance=RequestContext(request))
        else:
            return render_to_response('voting_page.html', {'form':form, 'send':False, 'election':election, 'user_key':user_key, 'show_already_voted':False, 'show_form':True, 'show_edit':edit_vote, 'show_vote_cast':False}, context_instance=RequestContext(request))

    else: # GET
        ballotForms=[]
        if edit_vote:
            for election_system in election.systems:
                ballot = Ballot.objects(system=election_system.system, election=election, user=user)[0]
                method_name = 'get_form_data_'+election_system.system.key
                method = globals()[method_name]
                form_data = method(ballot.content)
                ballot_method_name = election_system.system.key + 'BallotForm'
                ballot_method = globals()[ballot_method_name]
                ballotForms.append(ballot_method(choices=my_choices, custom=election_system.custom, initial=form_data))
        else:
            for election_system in election.systems:
                method_name = election_system.system.key + 'BallotForm'
                method = globals()[method_name]
                ballotForms.append(method(choices=my_choices, custom=election_system.custom))
        return render_to_response('voting_page.html', {'form':ballotForms[0], 'send':False, 'election':election, 'user_key':user_key, 'show_already_voted':already_voted and not edit_vote, 'show_form':(not already_voted) or edit_vote, 'show_edit':edit_vote, 'show_vote_cast':False}, context_instance=RequestContext(request))

def create(request):
    CandidateFormSet = formset_factory(CandidateForm, max_num=10, formset=RequiredFormSet) #TODO: make max_num a settings.py parameter (caution, 10 is used in js too)
    EmailGuestFormSet = formset_factory(EmailGuestForm, max_num=10, formset=RequiredFormSet) #TODO: idem
    if request.method == 'POST':
        election_form = ElectionForm(request.POST, request.FILES, prefix='election')
        creator_form = CreatorForm(request.POST, request.FILES, prefix='creator')
        candidate_formset = CandidateFormSet(request.POST, request.FILES, prefix='candidate')
        emailguest_formset = EmailGuestFormSet(request.POST, request.FILES, prefix='emailguest')
        customsystem_forms = dict()
        customs_are_valid = True
        for system in System.objects:
            method_name = system.key+'CustomForm'
            method = globals()[method_name]
            customsystem_form = method(request.POST, request.FILES, prefix=system.key+'_custom')
            if not customsystem_form.is_valid():
                customs_are_valid = False
            customsystem_form = customsystem_form.cleaned_data
            customsystem_forms[system.key] = customsystem_form
        if election_form.is_valid() and candidate_formset.is_valid() and emailguest_formset.is_valid() and creator_form.is_valid() and customs_are_valid:

electionapp/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About us!</h1>
{% endblock %}

electionapp/templates/account.html
{% extends "base.html" %}

{% block content %}
<h1>Create an account</h1>

<p><strong>{{ message }}</strong></p>

{% if not success %}
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"/>
</form>
{% endif %}

{% endblock %}

electionapp/templates/admin_election.html
{% extends "base.html" %}

{% block content %}
<h1>Admin page of the poll "{{election.name}}"</h1>
{% if election.open %}

<p>This election is still open. You need to close it to see the results. Caution, if you close it there is no going back!</p>
<form action="{% url 'electionapp.views.close_election' election.key|add:election.admin_key %}" method="POST">{% csrf_token %}
    <input type="submit" value="Close the election" />
</form>

<p>Guests:</p>
<ul>
{% for guest_key,guest in election.guests.items %}
<li>{{guest.email}} {% if election in guest.voted_in %}(voted){% else %}(did not vote){% endif %}</li>
{% endfor %}
</ul>

{% else %}

<p>The election is closed.
<form action="{% url 'electionapp.views.analyze_key' election.key %}" method="POST">{% csrf_token %}
    <input type="submit" value="See results" />
</form>
<form action="{% url 'electionapp.views.close_election' election.key|add:election.admin_key True %}" method="POST">{% csrf_token %}
    <input type="submit" value="Open election (dev only)" />
</form>

{% endif %}
{% endblock %}

electionapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
      <script src="//code.jquery.com/jquery-1.9.1.js"></script>
       <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
      {% block style %}{% endblock %}
      {% block javascript %}{% endblock %}
      <title>{% block title %}Waggled{% endblock %}</title>
  </head> 
  <body>
      <div id="header">
          {% block header %}
          [
          <a href="{% url 'electionapp.views.polls_overview' %}">All polls</a>
          <a href="{% url 'electionapp.views.users_overview' %}">All users</a>
          <a href="{% url 'electionapp.views.ballots_overview' %}">All ballots</a>
          <a href="{% url 'electionapp.views.results_overview' %}">All results</a>
          ]
          <a href="{% url 'electionapp.views.index' %}">Index</a>
          <a href="{% url 'electionapp.views.create' %}">Create a poll</a>
          
          {% if user.is_authenticated and not account_just_created %}
          {{user.name}}
          <a href="{% url 'electionapp.views.dashboard' %}">Dashboard</a>
          <a href="{% url 'electionapp.views.logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'electionapp.views.account' %}">Create an account</a>
          <a href="{% url 'electionapp.views.login' %}">Login</a>
          {% endif %}
          
          {% endblock %}
      </div>
      <div id="content">
      {% block content %}
      {% endblock %}
      </div>
  </body>
</html>

electionapp/templates/create.html
{% extends "base.html" %}

{% block javascript %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">

<script>
    $(function() {
      
      function updateEmailRequiredness() {
      var checked = $('#id_creator-invite_me').is(':checked');
      $('#id_creator-email').prop('required',checked);
      }
      
      function guestsVisibility() {
      var type =  $('input[name=election-type]:checked').val();
      if(type==1){
      $('.guests').show();
      $('.guests input').each(function(){$(this).prop('required',true);});
      }
      else{
      $('.guests').hide();
      $('.guests input').each(function(){$(this).prop('required',false);});
      }
      }
      
      function customsystemVisibility() {
      var key = $('#id_election-system').val();
      if(key=='RGV'){
      $('#RGV-slider').show();
      $('#id_RGV_custom-min').prop('required',true);
      $('#id_RGV_custom-max').prop('required',true);
      }
      else{
      $('#RGV-slider').hide();
      $('#id_RGV_custom-min').prop('required',false);
      $('#id_RGV_custom-max').prop('required',false);
      }
      }
      
      function inviteMeVisibility() {
      var type =  $('input[name=election-type]:checked').val();
      if(type==1){
      $('p #id_creator-invite_me').parent().show();
      }
      else{
      $('#id_creator-invite_me').parent().hide();
      }
      }
      
      $(window).load(function(event) {
                     guestsVisibility();
                     customsystemVisibility();
                     inviteMeVisibility();
                     updateEmailRequiredness();
                     });
      
      $('#id_election-system').change(function(event){customsystemVisibility()});
      $('#id_election-type').change(function(event){
                                    guestsVisibility();
                                    inviteMeVisibility();
                                    });
      $('#id_creator-invite_me').change(function(event){
                                        updateEmailRequiredness();
                                        });
      
    });
    
</script>

<script>
        $(function() {
          $( "#slider-range" ).slider({
                                      range: true,
                                      min: 0,
                                      max: 100,
                                      values: [ 0, 20 ],
                                      slide: function( event, ui ) {
                                        $( "#amount" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] );
                                        $('#id_RGV_custom-min').val(ui.values[0]);
                                        $('#id_RGV_custom-max').val(ui.values[1]);
                                      }
                                      });
          $( "#amount" ).val($( "#slider-range" ).slider( "values", 0 ) +
                             " - " + $( "#slider-range" ).slider( "values", 1 ) );
          });
        </script>

<script>
    var s_to_print = {'candidate': 'candidate', 'emailguest':'guest'};
    $(document).ready(function () {
                      
                      function updateElementIndex(el, prefix, ndx) {
                      var id_regex = new RegExp('(' + prefix + '-\\d+-)');
                      var replacement = prefix + '-' + ndx + '-';
                      if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,replacement));
                      if (el.id) el.id = el.id.replace(id_regex, replacement);
                      if (el.name) el.name = el.name.replace(id_regex, replacement);
                      }
                      
                      function deleteForm(btn, prefix, s) {
                      //s = typeof s !== 'undefined' ? s : 'candidate';
                      var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
                      if (formCount > 1) {
                      // Delete the item/form
                      $(btn).parents('.'+s).remove();
                      var forms = $('.'+s); // Get all the forms
                      // Update the total number of forms (1 less than before)
                      $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                      var i = 0;
                      // Go through the forms and set their indices, names and IDs
                      for (formCount = forms.length; i < formCount; i++) {
                      $(forms.get(i)).children().children().each(function () {
                                                                 if ($(this).attr('type') == 'text') updateElementIndex(this, prefix, i);
                                                                 });
                      }
                      } // End if
                      else {
                      alert("You have to enter at least one "+s_to_print[s]+"!");
                      }
                      return false;
                      }
                      
                      function addForm(btn, prefix, s) {
                      var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
                      // You can only submit a maximum of 10 candidates
                      if (formCount < 10) {
                      // Clone a form (without event handlers) from the first form
                      var row = $("."+s+":first").clone(false).get(0);
                      // Insert it after the last form
                      $(row).removeAttr('id').hide().insertAfter("."+s+":last").slideDown(300);
                      
                      // Remove the bits we don't want in the new row/form
                      // e.g. error messages
                      $(".errorlist", row).remove();
                      $(row).children().removeClass("error");
                      
                      // Relabel or rename all the relevant bits
                      $(row).children().children().each(function () {
                                                        updateElementIndex(this, prefix, formCount);
                                                        $(this).val("");
                                                        });
                      
                      // Add an event handler for the delete candidate/form link
                      $(row).find(".delete_"+s).click(function () {
                                                      return deleteForm(this, prefix, s);
                                                      });
                      // Update the total form count
                      $("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1);
                      } // End if
                      else {
                      alert("Sorry, you can only enter a maximum of ten "+s_to_print[s]+"s.");
                      }
                      return false;
                      }
                      
                      // Register the click event handlers
                      $("#add_candidate").click(function () {
                                                return addForm(this, 'candidate', 'candidate');
                                                });
                      $("#add_emailguest").click(function () {
                                                 return addForm(this, 'emailguest', 'emailguest');
                                                 });
                      
                      $(".delete_candidate").click(function () {
                                                   return deleteForm(this, 'candidate', 'candidate');
                                                   });
                      $(".delete_emailguest").click(function () {
                                                    return deleteForm(this, 'emailguest', 'emailguest');
                                                    });
                      
                      });
    </script>

{% endblock %}

{% block content %}
{% if success %}
    <p> Congratulations, your poll has been created!</p>
{% else %}
<h1>Create your poll!</h1>
<form action="{% url 'electionapp.views.create' %}" method="POST">{% csrf_token %}
    
    <div class='general'>
        <h2>General information</h2>
        {{ election_form.as_p }}
    </div>
    
    <div class='customsystem'>
        {% for key,customsystem_form in customsystem_forms.items %}
            {{ customsystem_form.as_p }}
        {% endfor %}
        <div id='RGV-slider' style="display:none">
            <p>
            <label for="amount">Range of grades:</label>
            <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;">
                </p>
            <div id="slider-range"></div>
        </div>
    </div>

        
    <div class='candidates'>
        <h2>Candidates</h2>
        {{ candidate_formset.management_form }}
        {% for form in candidate_formset.forms %}
        <div class="candidate">
            {{ form.as_p }}
            <p style=""><a class="delete_candidate" href="#">Delete</a></p>
        </div>
        {% endfor %}
        <p><a id="add_candidate" href="#">Add another candidate</a></p>
    </div>
    <div class='guests'>
        <h2>Guests</h2>
        {{ emailguest_formset.management_form }}
        {% for form in emailguest_formset.forms %}
        <div class="emailguest">
            {{ form.as_p }}
            <p style=""><a class="delete_emailguest" href="#">Delete</a></p>
        </div>
        {% endfor %}
        <p><a id="add_emailguest" href="#">Add another guest</a></p>
    </div>
    <div class='creator'>
        <h2>You</h2>
        {{ creator_form.as_p }}
    </div>
    <div class='submit'>
        <input type="submit" value=" Submit " />
    </div>
</form>
{% endif %}
{% endblock %}

electionapp/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<h1>Account dashboard</h1>

<p>Your polls:</p>
<ul>
{% for election in user.admin_of %}
<li><a href="{% url 'electionapp.views.analyze_key' election.key|add:election.admin_key %}">{{election.name}}</a> ({% if election.open %}Open{% else %}Closed{% endif %})</li>
{% endfor %}
</ul>

{% endblock %}

electionapp/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to Waggled!</h1>
<p><a href="{% url 'electionapp.views.create' %}">Create a poll</a></p>
<p><a href="{% url 'electionapp.views.systems' %}">Learn more about systems</a></p>
<p><a href="{% url 'electionapp.views.about' %}">About</a></p>
{% endblock %}

electionapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Log in</h1>

{% if error %}
<p><strong>Wrong email or password.</strong></p>
{% endif %}

{% if request.user.is_authenticated %}
You are logged in, {{ user.username }} !
{% else %}
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"/>
</form>
{% endif %}
{% endblock %}

electionapp/templates/voting_page.html
{% extends "base.html" %}

{% block style %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <style>
        #sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
        #sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
        #sortable li span { position: absolute; margin-left: -1.3em; }
        </style>
{% endblock %}

{% block javascript %}
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script>
        $(function() {
          
          function setRanking(rkg) {
            var arr = rkg.split(';');
            arr.pop()
            for(var i=arr.length-1; i>=0; i--) {
                $('#'+arr[i]).prependTo($('#sortable'));
            }
          }
          
          function setHiddenRanking() {
            var rkg = '';
            $('li').each(function() {
                                    rkg=rkg+$(this).attr('id')+';';
                                   });
            $('#id_ranking').attr('value',rkg);
          }
          
          
          $(window).load(function(event) {
                         var rkg = $('#id_ranking').attr('value');
                         if(rkg!=null){
                            setRanking(rkg);
                         }
                         else{
                            setHiddenRanking();
                         }
                         });
          
          $('#sortable').sortable({
                                  update: function(event, ui) {
                                  var rkg = '';
                                  $('.ui-state-default').each(function(){
                                                              rkg = rkg + $(this).attr('id')+';';
                                                              })
                                  $('#id_ranking').attr('value',rkg);
                                  }
                                  });
          $( "#sortable" ).disableSelection();
          });
        </script>
{% endblock %}

{% block content %}
<h1>Here you vote!</h1>

{% if show_edit %}
<p>Please edit your vote</p>
{% endif %}

{% if show_already_voted %}
<p>You voted already!</p>
<form action="{% url 'electionapp.views.edit_vote' election.key|add:user_key %}" method='get'>{% csrf_token %}
    <input type='submit' value='Edit your vote' />
</form>
{% endif %}

{% if form %}
{{ form.errors }}
{% endif %}

{% if show_vote_cast %}
Your vote has been cast all right!
{% endif %}

{% if show_form %}
{% if form.requires_ranking %}
<p>Please rank candidates.</p>
<ul id="sortable">
    {% for choice in form.choices %}
    <li class="ui-state-default" id="{{ choice.0 }}"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>{{ choice.1 }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'electionapp.views.analyze_key' election.key|add:user_key %}" method='post'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Submit' />
</form>
{% endif %}
{% endblock %}